language: rust
rust: stable

os:
- linux
- osx
- windows

matrix:
  allow_failures:
  - os: linux
  - os: windows

env:
  global:
  - RUSTFLAGS: "-Dwarnings"
  - RUST_BACKTRACE: "full"

cache:
  directories:
  - $HOME/.cargo

script: cargo test
